<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/link">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/link2">Link 2</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/link3">Link 3</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/link4">Link 4</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/link5">Link 5</a>
            </li>
        </ul>
    </div>
</nav>

<main role="main">
    <div class="container">
        <div class="pt-5">
            <h1 class="display-3">Hello, world!</h1>
        </div>
    </div>
</main>

